AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  Step function hello world with SAM!
Globals:
  Function:
    Runtime: "nodejs8.10"

Parameters:
  Env: 
    Type: String
    Default: dev

Resources:
  StreamProcessor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join [ -, [StreamProcessor, !Ref "Env"]]
      Handler: stream.handler
      CodeUri: src/
      Events:
        StreamEvent:
          Type: Kinesis
          Properties:
            Stream: !GetAtt K3.Arn
            StartingPosition: LATEST
            BatchSize: 50
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !Join [ -, [K3Q, !Ref "Env"]]
      Environment:
        Variables:
          DOWNSTREAM_Q_URL: !Ref Q3
  
  K3:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: !Join [ -, [K3Stream, !Ref "Env"]]
      ShardCount: 1

  Q3:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join [ -, [K3Q, !Ref "Env"]]
